### ISSUE TITLE
Ubuntu/Linux version.

### ISSUE THREAD

**Issue by APasz** [PhantomGamers/SteamFriendsPatcher#13]
A native version would be pretty great.

Got absolutely no idea what I'm doing with Wine so not sure if it works.

**Comment by PhantomGamers** [comment]
This would likely only work with Wine if you were also running Steam through Wine though I have no idea how it would actually work.

Eventually I'd like  to make a crossplatform version but it's less needed as on Linux you can modify the friends list and library both through webkit.css and it works a lot better than it does on Windows.

**Comment by APasz** [comment]
Ok thanks mate.

I'll look into the webkit.css.

**Comment by daemonspudguy** [comment]
How exactly does one customize the friends and library sections with webkit.css?

**Comment by Cheesegriller** [comment]
> How exactly does one customize the friends and library sections with webkit.css?

No idea, trying to figure it out myself.

**Comment by Cheesegriller** [comment]
> This would likely only work with Wine if you were also running Steam through Wine though I have no idea how it would actually work.
> 
> Eventually I'd like to make a crossplatform version but it's less needed as on Linux you can modify the friends list and library both through webkit.css and it works a lot better than it does on Windows.

I don't think that works anymore, I tried it last night and it won't work.

**Comment by tobedecided0601** [comment]
Pump this up as I use Linux as my main driver.

**Comment by PhantomGamers** [comment]
I don't run Linux so this won't be happening. At this point it looks like no one else will be contributing to enable linux compatibility.

**Comment by PhantomGamers** [comment]
I am working on a new version of the patcher written with multiplat in mind.

So far library scanning and patching works on Linux but I still need to get friends list patching working

![image](https://user-images.githubusercontent.com/844685/150693509-2b02f76c-ee87-4599-8534-b20046ea6e56.png)

Reopening this for now

**Comment by headassbtw** [comment]
any plans on releasing this version, even in an alpha state?

**Comment by PhantomGamers** [comment]
I've been posting alpha versions to the Unofficial Patch for Metro discord, the latest version for Linux is https://cdn.discordapp.com/attachments/623922408931459072/940834315200233522/SFP_UI-SelfContained-linux-x64-0.0.0-alpha.0.46.zip but it does not support the friends list as the cache files are in a different format on Linux and I could not figure out how to properly patch it. I will post up the repo within the next few weeks hopefully, it still needs some cleaning up before I do a proper release.

I'm not sure if I'll be able to figure out how to sort out friends patching on Linux but if anything the source code will be up if anyone wants to look at what I have already done

**Comment by PhantomGamers** [comment]
further linux support will occur over at https://github.com/PhantomGamers/SFP
