### ISSUE TITLE
Library Patch Beta not working since last Steam update

### ISSUE THREAD

**Issue by Hunter24681** [PhantomGamers/SteamFriendsPatcher#15]
I have been running Friends Patcher 0.1.20 with no issue and have custom styling for the client UI.  On the most recent steam update, it stopped working and reverted to default.  Thinking this was a Friends Patcher issue, I have updated to 0.1.36, but the issue persists.

Attached is an image of Steam css through launching steam in dev mode, my libraryroot.custom.css, which is in the correct directory, and the output of SFP gui through a couple launches of steam/force checks/cache clears.  

Play button class confirmation:
![Class of play button](https://user-images.githubusercontent.com/76822995/103423001-ef196400-4b69-11eb-8048-25d0549dca98.jpg)

Steam source shows default coloring:
![CSS file in Devtools Source Tab](https://user-images.githubusercontent.com/76822995/103423003-efb1fa80-4b69-11eb-9279-c59c0c727093.jpg)

Color change in my libraryroot.custom.css:
![Libraryroot custom file](https://user-images.githubusercontent.com/76822995/103423004-efb1fa80-4b69-11eb-80b2-9113e23ba089.jpg)

SFP output in trying to refresh things:
![SFP output](https://user-images.githubusercontent.com/76822995/103423006-efb1fa80-4b69-11eb-83b9-53abb00a5499.jpg)

**Comment by PhantomGamers** [comment]
Tick 'Steam Beta' in the patcher settings

**Comment by Hunter24681** [comment]
> Tick 'Steam Beta' in the patcher settings

Thank you so much!  I read the new notes about steam beta, but misinterpreted it as needing to opt into steam beta on steam.  Issue is fixed!
