### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by DeanSabbah** [PhantomGamers/SteamFriendsPatcher#19]
I'm new to github, so sorry if I'm reporting this wrong.

Steam Friends Patcher suddenly stopped working. I turned on debug mode and aside from the usual messages it gave me, this is what I saw.

> [2021-03-16 8:27:51 PM] [Debug] New file found: f_000165
> [2021-03-16 8:27:51 PM] [Debug] New file found: f_000166
> [2021-03-16 8:27:52 PM] [Debug] New file found: f_000167
> [2021-03-16 8:27:52 PM] [Debug] New file found: f_000168
> [2021-03-16 8:27:52 PM] [Debug] New file found: f_000169
> [2021-03-16 8:27:52 PM] [Debug] New file found: f_00016a
> [2021-03-16 8:27:52 PM] [Debug] New file found: f_00016b
> [2021-03-16 8:27:52 PM] [Debug] New file found: f_00016c
> [2021-03-16 8:27:52 PM] [Debug] f_000165 did not match.
> [2021-03-16 8:27:52 PM] [Debug] f_000165 did not match.
> [2021-03-16 8:27:52 PM] [Debug] f_000166 did not match.
> [2021-03-16 8:27:52 PM] [Debug] f_000166 did not match.
> [2021-03-16 8:27:53 PM] [Debug] f_000167 did not match.
> [2021-03-16 8:27:53 PM] [Debug] f_000167 did not match.
> [2021-03-16 8:27:53 PM] [Debug] f_000169 did not match.
> [2021-03-16 8:27:53 PM] [Debug] f_000168 did not match.
> [2021-03-16 8:27:53 PM] [Debug] f_000169 did not match.
> [2021-03-16 8:27:53 PM] [Debug] f_000168 did not match.
> [2021-03-16 8:27:53 PM] [Debug] f_00016a did not match.
> [2021-03-16 8:27:53 PM] [Debug] f_00016a did not match.
> [2021-03-16 8:27:53 PM] [Debug] f_00016b did not match.
> [2021-03-16 8:27:53 PM] [Debug] f_00016b did not match.
> [2021-03-16 8:27:53 PM] [Debug] f_00016c did not match.
> [2021-03-16 8:27:53 PM] [Debug] f_00016c did not match.
> [2021-03-16 8:28:07 PM] [Debug] New file found: f_00016d
> [2021-03-16 8:28:08 PM] [Debug] f_00016d did not match.
> [2021-03-16 8:28:08 PM] [Debug] f_00016d did not match.
> [2021-03-16 8:28:08 PM] [Debug] New file found: f_00016e
> [2021-03-16 8:28:08 PM] [Debug] New file found: f_00016f
> [2021-03-16 8:28:08 PM] [Debug] f_00016f did not match.
> [2021-03-16 8:28:08 PM] [Debug] f_00016f did not match.
> [2021-03-16 8:28:09 PM] [Debug] f_00016e did not match.
> [2021-03-16 8:28:09 PM] [Debug] f_00016e did not match.
> [2021-03-16 8:29:15 PM] [Debug] New file found: f_000170
> [2021-03-16 8:29:15 PM] [Debug] New file found: f_000171
> [2021-03-16 8:29:15 PM] [Debug] New file found: f_000172
> [2021-03-16 8:29:15 PM] [Debug] New file found: f_000173
> [2021-03-16 8:29:15 PM] [Debug] New file found: f_000174
> [2021-03-16 8:29:15 PM] [Debug] New file found: f_000175
> [2021-03-16 8:29:15 PM] [Debug] New file found: f_000176
> [2021-03-16 8:29:15 PM] [Debug] New file found: f_000177
> [2021-03-16 8:29:15 PM] [Debug] New file found: f_000178
> [2021-03-16 8:29:16 PM] [Debug] f_000170 did not match.
> [2021-03-16 8:29:16 PM] [Debug] f_000170 did not match.
> [2021-03-16 8:29:16 PM] [Debug] f_000171 did not match.
> [2021-03-16 8:29:16 PM] [Debug] f_000171 did not match.
> [2021-03-16 8:29:16 PM] [Debug] f_000172 did not match.
> [2021-03-16 8:29:16 PM] [Debug] f_000172 did not match.
> [2021-03-16 8:29:16 PM] [Debug] f_000173 did not match.
> [2021-03-16 8:29:16 PM] [Debug] f_000174 did not match.
> [2021-03-16 8:29:16 PM] [Debug] f_000175 did not match.
> [2021-03-16 8:29:16 PM] [Debug] f_000173 did not match.
> [2021-03-16 8:29:16 PM] [Debug] f_000174 did not match.
> [2021-03-16 8:29:16 PM] [Debug] f_000175 did not match.
> [2021-03-16 8:29:16 PM] [Debug] f_000177 did not match.
> [2021-03-16 8:29:16 PM] [Debug] f_000176 did not match.
> [2021-03-16 8:29:16 PM] [Debug] f_000177 did not match.
> [2021-03-16 8:29:16 PM] [Debug] f_000176 did not match.
> [2021-03-16 8:29:16 PM] [Debug] f_000178 did not match.
> [2021-03-16 8:29:16 PM] [Debug] f_000178 did not match.
> [2021-03-16 8:29:19 PM] [Debug] New file found: f_000179
> [2021-03-16 8:29:19 PM] [Debug] New file found: f_00017a
> [2021-03-16 8:29:19 PM] [Debug] New file found: f_00017b
> [2021-03-16 8:29:19 PM] [Debug] New file found: f_00017c
> [2021-03-16 8:29:19 PM] [Debug] New file found: f_00017d
> [2021-03-16 8:29:20 PM] [Debug] New file found: f_00017e
> [2021-03-16 8:29:20 PM] [Debug] f_000179 did not match.
> [2021-03-16 8:29:20 PM] [Debug] f_000179 did not match.
> [2021-03-16 8:29:20 PM] [Debug] New file found: f_00017f
> [2021-03-16 8:29:20 PM] [Debug] f_00017a did not match.
> [2021-03-16 8:29:20 PM] [Debug] f_00017b did not match.
> [2021-03-16 8:29:20 PM] [Debug] f_00017b did not match.
> [2021-03-16 8:29:20 PM] [Debug] f_00017a did not match.
> [2021-03-16 8:29:20 PM] [Debug] f_00017c did not match.
> [2021-03-16 8:29:20 PM] [Debug] f_00017d did not match.
> [2021-03-16 8:29:20 PM] [Debug] New file found: f_000180
> [2021-03-16 8:29:20 PM] [Debug] f_00017c did not match.
> [2021-03-16 8:29:20 PM] [Debug] f_00017d did not match.
> [2021-03-16 8:29:20 PM] [Debug] New file found: f_000181
> [2021-03-16 8:29:20 PM] [Debug] New file found: f_000182
> [2021-03-16 8:29:20 PM] [Debug] New file found: f_000183
> [2021-03-16 8:29:20 PM] [Debug] New file found: f_000184
> [2021-03-16 8:29:20 PM] [Debug] New file found: f_000185
> [2021-03-16 8:29:20 PM] [Debug] f_000180 did not match.
> [2021-03-16 8:29:20 PM] [Debug] f_000180 did not match.
> [2021-03-16 8:29:21 PM] [Debug] New file found: f_000186
> [2021-03-16 8:29:21 PM] [Debug] New file found: f_000187
> [2021-03-16 8:29:21 PM] [Debug] New file found: f_000188
> [2021-03-16 8:29:21 PM] [Debug] New file found: f_000189
> [2021-03-16 8:29:21 PM] [Debug] New file found: f_00018a
> [2021-03-16 8:29:21 PM] [Debug] New file found: f_00018b
> [2021-03-16 8:29:21 PM] [Debug] New file found: f_00018c
> [2021-03-16 8:29:21 PM] [Debug] New file found: f_00018d
> [2021-03-16 8:29:21 PM] [Debug] New file found: f_00018e
> [2021-03-16 8:29:21 PM] [Debug] New file found: f_00018f
> [2021-03-16 8:29:21 PM] [Debug] New file found: f_000190
> [2021-03-16 8:29:21 PM] [Debug] New file found: f_000191
> [2021-03-16 8:29:21 PM] [Debug] New file found: f_000192
> [2021-03-16 8:29:21 PM] [Debug] New file found: f_000193
> [2021-03-16 8:29:21 PM] [Debug] New file found: f_000194
> [2021-03-16 8:29:21 PM] [Debug] New file found: f_000195
> [2021-03-16 8:29:21 PM] [Debug] New file found: f_000196
> [2021-03-16 8:29:21 PM] [Debug] New file found: f_000197
> [2021-03-16 8:29:21 PM] [Debug] New file found: f_000198
> [2021-03-16 8:29:21 PM] [Debug] f_00017e did not match.
> [2021-03-16 8:29:21 PM] [Debug] New file found: f_000199
> [2021-03-16 8:29:21 PM] [Debug] New file found: f_00019a
> [2021-03-16 8:29:21 PM] [Debug] New file found: f_00019b
> [2021-03-16 8:29:21 PM] [Debug] New file found: f_00019c
> [2021-03-16 8:29:21 PM] [Debug] New file found: f_00019d
> [2021-03-16 8:29:21 PM] [Debug] New file found: f_00019e
> [2021-03-16 8:29:21 PM] [Debug] f_00017e did not match.
> [2021-03-16 8:29:21 PM] [Debug] New file found: f_00019f
> [2021-03-16 8:29:21 PM] [Debug] New file found: f_0001a0
> [2021-03-16 8:29:21 PM] [Debug] New file found: f_0001a1
> [2021-03-16 8:29:21 PM] [Debug] New file found: f_0001a2
> [2021-03-16 8:29:21 PM] [Debug] f_00017f did not match.
> [2021-03-16 8:29:21 PM] [Debug] f_00017f did not match.
> [2021-03-16 8:29:21 PM] [Debug] f_000181 did not match.
> [2021-03-16 8:29:21 PM] [Debug] f_000181 did not match.
> [2021-03-16 8:29:21 PM] [Debug] f_000182 did not match.
> [2021-03-16 8:29:21 PM] [Debug] f_000182 did not match.
> [2021-03-16 8:29:21 PM] [Debug] New file found: f_0001a3
> [2021-03-16 8:29:21 PM] [Debug] New file found: f_0001a4
> [2021-03-16 8:29:21 PM] [Debug] f_000183 did not match.
> [2021-03-16 8:29:21 PM] [Debug] f_000183 did not match.
> [2021-03-16 8:29:21 PM] [Debug] f_000184 did not match.
> [2021-03-16 8:29:21 PM] [Debug] f_000184 did not match.
> [2021-03-16 8:29:21 PM] [Debug] f_000185 did not match.
> [2021-03-16 8:29:21 PM] [Debug] f_000185 did not match.
> [2021-03-16 8:29:21 PM] [Debug] f_00018f did not match.
> [2021-03-16 8:29:21 PM] [Debug] f_00018e did not match.
> [2021-03-16 8:29:21 PM] [Debug] f_00018e did not match.
> [2021-03-16 8:29:21 PM] [Debug] f_00018f did not match.
> [2021-03-16 8:29:21 PM] [Debug] f_000190 did not match.
> [2021-03-16 8:29:21 PM] [Debug] f_000191 did not match.
> [2021-03-16 8:29:21 PM] [Debug] f_000192 did not match.
> [2021-03-16 8:29:21 PM] [Debug] f_000193 did not match.
> [2021-03-16 8:29:21 PM] [Debug] f_000190 did not match.
> [2021-03-16 8:29:21 PM] [Debug] f_000191 did not match.
> [2021-03-16 8:29:21 PM] [Debug] f_000192 did not match.
> [2021-03-16 8:29:21 PM] [Debug] f_000195 did not match.
> [2021-03-16 8:29:21 PM] [Debug] f_000194 did not match.
> [2021-03-16 8:29:21 PM] [Debug] f_000193 did not match.
> [2021-03-16 8:29:21 PM] [Debug] f_000196 did not match.
> [2021-03-16 8:29:21 PM] [Debug] f_000197 did not match.
> [2021-03-16 8:29:21 PM] [Debug] f_000198 did not match.
> [2021-03-16 8:29:21 PM] [Debug] f_000195 did not match.
> [2021-03-16 8:29:21 PM] [Debug] f_000194 did not match.
> [2021-03-16 8:29:21 PM] [Debug] f_00019a did not match.
> [2021-03-16 8:29:21 PM] [Debug] f_000199 did not match.
> [2021-03-16 8:29:21 PM] [Debug] f_00019b did not match.
> [2021-03-16 8:29:21 PM] [Debug] f_00019c did not match.
> [2021-03-16 8:29:21 PM] [Debug] f_000196 did not match.
> [2021-03-16 8:29:21 PM] [Debug] f_000197 did not match.
> [2021-03-16 8:29:21 PM] [Debug] f_000198 did not match.
> [2021-03-16 8:29:21 PM] [Debug] f_00019e did not match.
> [2021-03-16 8:29:21 PM] [Debug] f_00019d did not match.
> [2021-03-16 8:29:21 PM] [Debug] f_0001a0 did not match.
> [2021-03-16 8:29:21 PM] [Debug] f_00019f did not match.
> [2021-03-16 8:29:21 PM] [Debug] f_00019a did not match.
> [2021-03-16 8:29:21 PM] [Debug] f_000199 did not match.
> [2021-03-16 8:29:21 PM] [Debug] f_0001a1 did not match.
> [2021-03-16 8:29:21 PM] [Debug] f_0001a2 did not match.
> [2021-03-16 8:29:21 PM] [Debug] f_00019b did not match.
> [2021-03-16 8:29:21 PM] [Debug] f_00019c did not match.
> [2021-03-16 8:29:22 PM] [Debug] f_00019e did not match.
> [2021-03-16 8:29:22 PM] [Debug] f_00019d did not match.
> [2021-03-16 8:29:22 PM] [Debug] f_0001a0 did not match.
> [2021-03-16 8:29:22 PM] [Debug] f_00019f did not match.
> [2021-03-16 8:29:22 PM] [Debug] f_0001a1 did not match.
> [2021-03-16 8:29:22 PM] [Debug] f_0001a2 did not match.
> [2021-03-16 8:29:22 PM] [Debug] f_0001a3 did not match.
> [2021-03-16 8:29:22 PM] [Debug] f_0001a3 did not match.
> [2021-03-16 8:29:22 PM] [Debug] f_0001a4 did not match.
> [2021-03-16 8:29:22 PM] [Debug] f_0001a4 did not match.
> [2021-03-16 8:29:22 PM] [Debug] f_000186 did not match.
> [2021-03-16 8:29:22 PM] [Debug] f_000186 did not match.
> [2021-03-16 8:29:22 PM] [Debug] f_000189 did not match.
> [2021-03-16 8:29:22 PM] [Debug] f_000188 did not match.
> [2021-03-16 8:29:22 PM] [Debug] f_000187 did not match.
> [2021-03-16 8:29:22 PM] [Debug] f_000189 did not match.
> [2021-03-16 8:29:22 PM] [Debug] f_000188 did not match.
> [2021-03-16 8:29:22 PM] [Debug] f_000187 did not match.
> [2021-03-16 8:29:22 PM] [Debug] f_00018a did not match.
> [2021-03-16 8:29:22 PM] [Debug] f_00018b did not match.
> [2021-03-16 8:29:22 PM] [Debug] f_00018a did not match.
> [2021-03-16 8:29:22 PM] [Debug] f_00018d did not match.
> [2021-03-16 8:29:22 PM] [Debug] f_00018c did not match.
> [2021-03-16 8:29:22 PM] [Debug] f_00018b did not match.
> [2021-03-16 8:29:22 PM] [Debug] f_00018d did not match.
> [2021-03-16 8:29:22 PM] [Debug] f_00018c did not match.
> [2021-03-16 8:29:24 PM] [Debug] New file found: f_0001a5
> [2021-03-16 8:29:24 PM] [Debug] f_0001a5 did not match.
> [2021-03-16 8:29:24 PM] [Debug] f_0001a5 did not match.
> [2021-03-16 8:29:27 PM] [Debug] Library change detected.
> [2021-03-16 8:29:27 PM] [Info] Patching Library [BETA]...
> [2021-03-16 8:29:27 PM] [Info] Library already patched.
> [2021-03-16 8:29:36 PM] [Debug] New file found: f_0001a6
> [2021-03-16 8:29:36 PM] [Debug] f_0001a6 did not match.
> [2021-03-16 8:29:36 PM] [Debug] f_0001a6 did not match.
> [2021-03-16 8:31:32 PM] [Debug] New file found: f_0001a5
> [2021-03-16 8:31:33 PM] [Debug] f_0001a5 did not match.
> [2021-03-16 8:31:33 PM] [Debug] f_0001a5 did not match.

Again, sorry if I'm doing this wrong.

**Comment by PhantomGamers** [comment]
What do you mean by "stopped working?" What exactly isn't working?

The friends list skin? The library?

The log you posted is incomplete, so all I can see is that it detected that the library is already patched so that should be working.

I recommend using the "clear cache" option in the patcher whenever you run into problems as quite often simply clearing the cache and patching again (making sure to restart Steam after patching) will solve your problems.

**Comment by DeanSabbah** [comment]
Hi, thanks for the quick reply. I should have been more specific. Neither the library nor the friends list works (Though now the [side bar in the library does work sometimes](https://i.imgur.com/dd44WGj.jpg)). I have already tried clearing the cache and repatching multiple times but nothing really happened. Also, I do have a [screenshot](https://i.imgur.com/xAt52Y0.jpg) of the beginning of the logs.

Also, I feel that I should mention that I do have the Steam BETA option enabled.

**Comment by PhantomGamers** [comment]
The library issue is due to the skin you are using (https://github.com/AikoMidori/steam-library)

There is a server outage due to the OVH data center fire, so the website the files are hosted on (if you're using the live.css file) is unavailable.

As for the friends list, you might have to restart Steam once more and spam the force check button on the patcher a bit, because the patcher is only getting etag `Rz_LEzy00gy4` right now but Steam is currently distributing etag `718jaoKz2Vlj` as well.

**Comment by DeanSabbah** [comment]
Oh, I didn't know there was a server fire! Thanks for helping me figure this out. I tried with another skin and it worked... I probably should have started with that.
