### ISSUE TITLE
No .exe file :D

### ISSUE THREAD

**Issue by mindelekas** [PhantomGamers/SteamFriendsPatcher#20]
So I tried to download SteamFriendsPatcher. Extracted, but there is not SteamFriendsPatcher.exe file. Fail :D

pls fix.
![steamfriendspatcher](https://user-images.githubusercontent.com/85796045/121778975-245ac100-cba2-11eb-873c-55ef26aa95ce.png)

**Comment by PhantomGamers** [comment]
You downloaded the source code instead of the release
