### ISSUE TITLE
[Question] How do I uninstall this?

### ISSUE THREAD

**Issue by Senna0202** [PhantomGamers/SteamFriendsPatcher#23]
Hello, 

Apologies for putting this in the issues tab, I had no other way of doing this. I can't seem to figure out how to properly uninstall this. I've deleted some files and so on, but I'm not confident I uninstalled it properly. How can I go about doing this? 

Thanks in advance.

**Comment by PhantomGamers** [comment]
Running "Clear Cache" in the patcher should be enough to uninstall it, make sure to disable auto scanning before doing this otherwise it'll just repatch right away.
