### ISSUE TITLE
stuck in patching library

### ISSUE THREAD

**Issue by ghost** [PhantomGamers/SteamFriendsPatcher#25]
hi! I'm using the latest version of the patcher and it's always stuck in patching library (beta). is there any way to fix this? i've also tried making steam part of the beta program while patching, and it's still stuck. thanks!

> [12/15/2021 8:40:31 PM] [Info] Checking for updates...
> [12/15/2021 8:40:32 PM] [Info] Checking for latest friends.css...
> [12/15/2021 8:40:32 PM] [Info] No updates found.
> [12/15/2021 8:40:33 PM] [Info] Downloaded friends.css with etag: "vaWWEATW6BrN"
> [12/15/2021 8:40:34 PM] [Info] Downloaded friends.css with etag: "vaWWEATW6BrN"
> [12/15/2021 8:40:34 PM] [Info] Successfully downloaded friends.css files.
> [12/15/2021 8:40:34 PM] [Info] Cache Watcher Started.
> [12/15/2021 8:40:34 PM] [Info] Cache Watcher Stopped.
> [12/15/2021 8:40:34 PM] [Info] Force scan started.
> [12/15/2021 8:40:34 PM] [Info] Finding list of possible cache files...
> [12/15/2021 8:40:34 PM] [Info] Found 1520 possible cache files.
> [12/15/2021 8:40:34 PM] [Info] Checking cache files for match...
> [12/15/2021 8:40:35 PM] [Info] Cache file is already patched.
> [12/15/2021 8:40:35 PM] [Info] Patching Library [BETA]...

**Comment by PhantomGamers** [comment]
If you are able to get into the settings of the patcher, make sure the Library CSS setting is set to `6.css`

If you are unable to get into the settings, press windows key + R and then type in `%localappdata%/PhantomGamers` and look for the most recently updated folder if there are multiple, go into it and open the `user.config` file in a text editor like notepad and change:
```
<setting name="libraryRootCss" serializeAs="String">
    <value>6.css</value>
</setting>
```
so that the `<value>` line looks like that

Next time I have some free time I'll work on an update to the program to prevent this from happening in the future

**Comment by ghost** [comment]
Thanks for this, @PhantomGamers ! The patching went through. I restarted Steam with the skin I wanted to add already selected on settings and the skin was successfully applied on my Steam client. But now, the patcher's stuck on Cache Watcher Started.

> [12/15/2021 11:17:08 PM] [Info] Checking for updates...
> [12/15/2021 11:17:09 PM] [Info] Checking for latest friends.css...
> [12/15/2021 11:17:09 PM] [Info] Downloaded friends.css with etag: "vaWWEATW6BrN"
> [12/15/2021 11:17:09 PM] [Info] Downloaded friends.css with etag: "heNcHRx0TAKO"
> [12/15/2021 11:17:09 PM] [Info] Successfully downloaded friends.css files.
> [12/15/2021 11:17:09 PM] [Info] Cache Watcher Started.
> [12/15/2021 11:17:09 PM] [Info] Cache Watcher Stopped.
> [12/15/2021 11:17:09 PM] [Info] Force scan started.
> [12/15/2021 11:17:09 PM] [Info] No updates found.
> [12/15/2021 11:17:09 PM] [Info] Finding list of possible cache files...
> [12/15/2021 11:17:09 PM] [Info] Found 1388 possible cache files.
> [12/15/2021 11:17:09 PM] [Info] Checking cache files for match...
> [12/15/2021 11:17:10 PM] [Info] Cache file is already patched.
> [12/15/2021 11:17:10 PM] [Info] Patching Library [BETA]...
> [12/15/2021 11:17:10 PM] [Info] Library patched! [BETA]
> [12/15/2021 11:17:10 PM] [Info] Put custom library css in d:\steam\steamui\libraryroot.custom.css
> [12/15/2021 11:17:10 PM] [Info] Cache Watcher Started.
> [12/15/2021 11:20:04 PM] [Info] Cache Watcher Stopped.
> [12/15/2021 11:20:04 PM] [Info] Force scan started.
> [12/15/2021 11:20:04 PM] [Info] Checking for latest friends.css...
> [12/15/2021 11:20:05 PM] [Info] Downloaded friends.css with etag: "vaWWEATW6BrN"
> [12/15/2021 11:20:05 PM] [Info] Downloaded friends.css with etag: "heNcHRx0TAKO"
> [12/15/2021 11:20:05 PM] [Info] Successfully downloaded friends.css files.
> [12/15/2021 11:20:05 PM] [Info] Finding list of possible cache files...
> [12/15/2021 11:20:05 PM] [Info] Found 1390 possible cache files.
> [12/15/2021 11:20:05 PM] [Info] Checking cache files for match...
> [12/15/2021 11:20:06 PM] [Info] Cache file is already patched.
> [12/15/2021 11:20:06 PM] [Info] Patching Library [BETA]...
> [12/15/2021 11:20:06 PM] [Info] Library already patched.
> [12/15/2021 11:20:06 PM] [Info] Cache Watcher Started.

**Comment by PhantomGamers** [comment]
Seems fine to me, according to that log the patcher did its job. What is the issue?

**Comment by ghost** [comment]
So I don't need to do anything after the "Cache Watcher Started"? I'm sorry, I have 0 knowledge when it comes to these things 
😅

**Comment by PhantomGamers** [comment]
Not if it's working, the cache watcher is just something that will run in the background (if you keep the program active/in your system tray) to try to detect updates to Steam so that it can automatically repatch the files as needed.

I'm going to close this but if you run into any other problems or have any other questions feel free to open another issue :)
