### ISSUE TITLE
Steam directory not found

### ISSUE THREAD

**Issue by CallOfJuarez** [PhantomGamers/SteamFriendsPatcher#29]
For whatever reason the patcher can no longer find the Steam directory. Also when I click on the settings icon it just crashes.
![sfp](https://user-images.githubusercontent.com/81934509/153581430-87efde72-77ec-4f9b-8c4d-8e6f695c04b8.png)

Although the patcher stopped working right after a Windows update, so maybe that did something?

**Comment by PhantomGamers** [comment]
Can you post the crash log?

You should see it by opening `Event Viewer` and then going to Windows Logs -> Application

As for it not finding the Steam directory, maybe try reinstalling Steam over your current installation. 

The patcher looks for your Steam directory in your registry at `Computer\HKEY_CURRENT_USER\Software\Valve\Steam` under the key `SteamPath`, so if it is unable to find that it's not going to function.

**Comment by CallOfJuarez** [comment]
As for the registry, SteamPath is there.
![steampath](https://user-images.githubusercontent.com/81934509/153709535-79d4864f-0760-4dd7-87b8-eee2292ff93f.png)

Event viewer (while it's not in English hopefully you can parse it):

Název chybující aplikace: SteamFriendsPatcher.exe, verze: 0.1.41.1, časové razítko: 0x618736b7
Název chybujícího modulu: KERNELBASE.dll, verze: 10.0.22000.434, časové razítko: 0x78dc11b6
Kód výjimky: 0xe0434352
Posun chyby: 0x0013ec52
ID chybujícího procesu: 0x1ba8
Čas spuštění chybující aplikace: 0x01d81f36e0d847e7
Cesta k chybující aplikaci: C:\Programs\Steam Friends Patcher\SteamFriendsPatcher.exe
Cesta k chybujícímu modulu: C:\WINDOWS\System32\KERNELBASE.dll
ID zprávy: d7a0050b-a396-4b58-8e10-e0a7579125ae
Úplný název chybujícího balíčku: 
ID aplikace související s chybujícím balíčkem:

**Comment by CallOfJuarez** [comment]
Okay, I don't know what I did but the patcher works now, either turning my PC on and off or changing the SteamPath registry key from c:/programs/steam to C:\Programs\Steam did the trick.
