### ISSUE TITLE
Library CSS Not Found and Issue on the Buttons

### ISSUE THREAD

**Issue by ElysiumLeoSK** [PhantomGamers/SteamFriendsPatcher#31]
Hello! I have two issues to report.

First is that it doesn't auto detect the Library CSS (specifically the OG Steam Library Skin) and I do not know how to resolve it. Is there anyway I can do? Please refer to [this screenshot](https://i.imgur.com/fnSnAqk.png) to know what I'm talking about.

Second is that I cannot see the texts that are inputted on the buttons on the cogwheel menu of the patcher. See the [screenshot](https://i.imgur.com/pIII4tP.png) to know what I'm referring to. Anything I can do about these two problems?

**Comment by katawajojo** [comment]
The Library CSS file is now "library.css".

Change that, then click the far left button. 
![image](https://user-images.githubusercontent.com/13071927/160600459-fcd3e569-34fa-4b6a-a8c1-83936ad8a977.png)

**Comment by PhantomGamers** [comment]
In general the file you should target should be the largest file in `Steam/steamui/css`

Currently on the latest Steam beta this is 2.css

**Comment by ElysiumLeoSK** [comment]
Thank you, both of you! I got it fixed.
