### ISSUE TITLE
Internet information invisible on download page

### ISSUE THREAD

**Issue by CallOfJuarez** [PhantomGamers/SteamFriendsPatcher#32]
Using [MetroForSteam](https://metroforsteam.com) with [Unofficial Patch](https://steamcommunity.com/groups/metroskin/discussions/0/141136086931804907) 

With library patch:
![Snímek obrazovky (19)](https://user-images.githubusercontent.com/81934509/163484511-51a1af74-f6f5-409d-ad26-81ae7f9c1b2e.png)
Without library patch:
![Snímek obrazovky (20)](https://user-images.githubusercontent.com/81934509/163484518-6024a224-fc39-40d7-9ec8-e848944c7bc1.png)

Before only the graph disappeared moving the download info next to the game logo but now that is gone too (can still access download settings by clicking the download limit, looks like the info is only invisible)

Any ideas?

**Comment by PhantomGamers** [comment]
Make sure that the patcher is set to patch the correct library css in the settings. Currently on Steam stable this is 1.css, last I checked it was 2.css on the beta branch but in general it is going to be the largest file in the Steam/steamui/css folder

**Comment by CallOfJuarez** [comment]
Still the same.

**Comment by PhantomGamers** [comment]
Must be an issue with whatever library skin you are using then, for me using [Shiina's skin](https://github.com/AikoMidori/steam-library) it looks fine

![image](https://user-images.githubusercontent.com/844685/163549717-0de1c1fc-c569-46db-a950-0f77db4bf21b.png)

**Comment by CallOfJuarez** [comment]
The graph is still gone in your screenshot.
Gonna try if I have the same issue with your skin.

**Comment by PhantomGamers** [comment]
> The graph is still gone in your screenshot.

The internet information is not invisible though. I believe the skin I use just does not have the graph. Either way this is not an issue with the patcher

**Comment by CallOfJuarez** [comment]
![Snímek obrazovky (21)](https://user-images.githubusercontent.com/81934509/163551729-6b13ecf2-df9c-44e1-a761-a1ec9198f4c4.png)
![Snímek obrazovky (22)](https://user-images.githubusercontent.com/81934509/163551750-809c646f-11ca-4460-8118-c4473e0f2070.png)
![Snímek obrazovky (22)4](https://user-images.githubusercontent.com/81934509/163555487-fd4f5a1a-b5a0-472a-917b-d8fb967a80a6.png)
Looks like for whatever reason the game art is in front of the info.

**Comment by PhantomGamers** [comment]
This is something that should be reported to the skin developer
