### ISSUE TITLE
How to uninstall? Friends it's just a black box now...

### ISSUE THREAD

**Issue by MoneyAllDay** [PhantomGamers/SteamFriendsPatcher#5]
I used this tool for the "[Metro skin for new Steam chat and friends UI](https://github.com/RoseTheFlower/newsteamchat)" but it looks like users need to have this tool running at every windows/steam start and i don't want that.

Now, how do i **revert back what this tool did**? Steam friends now it's just a [black box](https://i.imgur.com/E5uVp41.png) no matter what i do.

I instaled steam over in the same location without uninstaling steam.
I deleted all files in steam installation folder except for "steamapps" and "Steam.exe", started steam.

Please, what can i do?

EDIT: F*ck me, i forgot about "userdata" sigh.... Well there goes all my screenshots. Anyway, i just reinstalled steam and it's fine now but it would be nice to still know how to revert it back.

**Comment by PhantomGamers** [comment]
The reason your friends list turned black is likely because you deleted the friends.custom.css without reverting the patch. You can revert/uninstall the patch by using the clear cache button in the patcher.
